on:
  workflow_call:
    secrets:
      FETCH_TOKEN:
        required: false

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.FETCH_TOKEN || github.token }}

      - uses: wagoid/commitlint-github-action@v6.2.1
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
