name: Test ForgingBlazor.Abstractions

on:
  pull_request:
    branches:
      - main

jobs:
  execute:
    uses: ./.github/workflows/execute-dotnet.yml
    with:
      dotnet-version: 9.x
      dotnet-solution: ./tests/abstractions/ForgingBlazor.Abstractions.sln
    secrets: inherit
