on:
  pull_request:
    branches:
      - main

jobs:
  execute:
    name: Test ForgingBlazor.Abstractions
    uses: ./.github/workflows/execute-dotnet.yml
    with:
      dotnet-version: 9.x
      dotnet-solution: ./tests/abstractions/ForgingBlazor.Abstractions.sln
    secrets: inherit
